[local]
localhost

[mongodb]
mongodb.janadevops.online

[redis]
redis.janadevops.online

[mysql]
mysql.janadevops.online

[rabbitmq]
rabbitmq.janadevops.online

[catalogue]
catalogue.janadevops.online

[user]
user.janadevops.online

[cart]
cart.janadevops.online

[shipping]
shipping.janadevops.online

[payment]
payment.janadevops.online

[frontend]
frontend.janadevops.online