---
- import_role:
    name: common
    tasks_from: nodejs

- import_role:
    name: common
    tasks_from: app-setup

- name: Install NodeJS dependencies
  community.general.npm:
    path: /app

- name: Copy Mongo repo
  copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install MongoDB client
  package:
    name: mongodb-mongosh
    state: present

- name: Check catalogue schema
  shell: mongosh --host "{{ MONGODB_HOST }}" --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: Load catalogue schema
  shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: catalogue_output.stdout | int < 0

- import_role:
    name: common
    tasks_from: systemd-setup

- import_role:
    name: common
    tasks_from: restart


- import_role:
    name: common
    tasks_from: nodejs    